### PR TITLE
Animal farm game made on Unity using C#

### PR DESCRIPTION
**Pull request by harshitajain165**
<h1 align= "center"> 🌴  Description  👨‍🌾  </h1>

- Created on `Unity Engine` using `C#`, Animal Farm is a simple yet engaging game for PC where the player (farmer) navigates horizontally on being controlled by the ◀️  and ▶️  keys.
- The aim of the player is to prevent the animals from crossing the boundary of the farm by aiming discs at them using the spacebar key.
- The animals disappear when the player successfully aims the disc at them.
- The game ends as soon an animal crosses the boundary.
<hr>

<hr>
The given project was created with the reference and assistance of Unity's Junior Programmer Course. For anyone who wishes to learn Unity or game development, this course is the ideal starting point.
<h3>

<a href = "https://learn.unity.com/mission/programming-basics?pathwayId=5f7e17e1edbc2a5ec21a20af" target="_blank">Link to the course</a>  
</h3>
<hr> 

Checklist

- [x] I have added proper documentation for my contribution.
- [x] I have added myself in `contributors.json`.
- [x] My contribution isn't already present in the repository.
- [x] My contribution is working.
- [x] My changes don't generate any new warnings.
- [x] My changes don't affect any work done by other developers. 

To tick a box, replace `[ ]` with `[x]`.

### CODE REVIEW

**Review by ashutoshkrris — CHANGES_REQUESTED** [review]
Hey @harshitajain165 
The project looks amazing!
Could you please add proper documentation in your README file describing what it is about, how one can get started? You can use screenshots for the same.

**Comment by harshitajain165** [comment]
Hi
Sure I would do the same in a while!
Regards
Harshita Jain

**Comment by harshitajain165** [comment]
> 
> 
> Hey @harshitajain165 The project looks amazing! Could you please add proper documentation in your README file describing what it is about, how one can get started? You can use screenshots for the same.

Updated the README with the relevant information and link to an ideal course for beginners. Hope it would help!

**Comment by ashutoshkrris** [comment]
Hey @harshitajain165 
Looks like you didn't update the README, but just the PR description
Please update the README available here : https://github.com/harshitajain165/Hacktoberfest-Contribution/blob/master/contributions/Animal%20Farm/README.md
And push the changes to update the PR

**Pull request closed without merging**
